(() => {
  "use strict";

  const API_URL = "https://script.google.com/macros/s/AKfycbzalC81iNvpLXuymmbMVI4pYB1FzuTXHgnvG4kegKspl7Mfd5j11BGW9W5Gv9xXsM1lMg/exec";
  const API_TOKEN = "hBsuU2uyQQ6WO3MbA30DtVLb2SJhuiblRqH77g1Ns9M";
  const state = { loaded:false, loading:false, unread:0, messages:[] };

  const labels = {
    pl:{title:"Poczta / Zgłoszenia",sub:"Wiadomości z formularza Europris",panel:"Zgłoszenia Europris",refresh:"Odśwież",loading:"Sprawdzanie poczty…",empty:"Brak zgłoszeń.",error:"Nie udało się pobrać zgłoszeń.",read:"Oznacz jako przeczytane",readDone:"Przeczytane",contact:"Kontakt",version:"Wersja",type:"Rodzaj",new:"nowe"},
    no:{title:"E-post / Meldinger",sub:"Meldinger fra Europris-skjemaet",panel:"Europris-meldinger",refresh:"Oppdater",loading:"Sjekker e-post…",empty:"Ingen meldinger.",error:"Kunne ikke hente meldinger.",read:"Marker som lest",readDone:"Lest",contact:"Kontakt",version:"Versjon",type:"Type",new:"nye"},
    en:{title:"Mail / Reports",sub:"Messages from the Europris form",panel:"Europris reports",refresh:"Refresh",loading:"Checking mail…",empty:"No reports.",error:"Could not load reports.",read:"Mark as read",readDone:"Read",contact:"Contact",version:"Version",type:"Type",new:"new"},
    de:{title:"E-Mail / Meldungen",sub:"Nachrichten aus dem Europris-Formular",panel:"Europris-Meldungen",refresh:"Aktualisieren",loading:"E-Mail wird geprüft…",empty:"Keine Meldungen.",error:"Meldungen konnten nicht geladen werden.",read:"Als gelesen markieren",readDone:"Gelesen",contact:"Kontakt",version:"Version",type:"Typ",new:"neu"}
  };

  function lang(){const v=String(document.documentElement.lang||"pl").toLowerCase();if(v.startsWith("no")||v.startsWith("nb")||v.startsWith("nn"))return"no";if(v.startsWith("en"))return"en";if(v.startsWith("de"))return"de";return"pl";}
  function t(){return labels[lang()]||labels.pl;}
  function panelOpen(){const panel=document.getElementById("adminPanel");return !!panel&&!panel.hidden&&getComputedStyle(panel).display!=="none";}
  function isAndrzejAdmin(){if(!panelOpen())return false;const profile=document.getElementById("adminProfileSection");if(profile&&!profile.hidden&&getComputedStyle(profile).display!=="none")return true;const title=String(document.getElementById("adminTitle")?.textContent||"").toLowerCase();return title.includes("andrzej");}
  function jsonp(action,params={}){return new Promise((resolve,reject)=>{const cb=`__europrisMail_${Date.now()}_${Math.random().toString(36).slice(2)}`,s=document.createElement("script");let done=false;const cleanup=()=>{if(done)return;done=true;clearTimeout(timer);delete window[cb];s.remove();};const timer=setTimeout(()=>{cleanup();reject(new Error("timeout"));},20000);window[cb]=data=>{cleanup();resolve(data);};const q=new URLSearchParams({action,token:API_TOKEN,callback:cb,_:String(Date.now()),...params});s.src=`${API_URL}?${q}`;s.onerror=()=>{cleanup();reject(new Error("network"));};document.head.appendChild(s);});}

  function positionUi(){const wrap=document.getElementById("adminMailWrap");if(!wrap)return;const humor=document.getElementById("dailyHumorCard");if(humor&&humor.parentElement){if(humor.nextElementSibling!==wrap)humor.insertAdjacentElement("afterend",wrap);return;}const adminPanel=document.getElementById("adminPanel");if(adminPanel&&wrap.parentElement!==adminPanel)adminPanel.appendChild(wrap);}
  function ensureUi(){if(document.getElementById("adminMailWrap")){positionUi();return;}const adminPanel=document.getElementById("adminPanel");if(!adminPanel)return;const wrap=document.createElement("section");wrap.id="adminMailWrap";wrap.className="admin-mail-wrap";wrap.hidden=true;wrap.innerHTML=`<button id="adminMailTile" class="admin-mail-tile" type="button" aria-expanded="false"><span class="admin-mail-tile-text"><span class="admin-mail-tile-title"></span><span class="admin-mail-tile-sub"></span></span><span id="adminMailBadge" class="admin-mail-badge zero">0</span><span class="admin-mail-arrow">⌄</span></button><section id="adminMailPanel" class="admin-mail-panel" hidden><div class="admin-mail-head"><strong id="adminMailPanelTitle"></strong><button id="adminMailRefresh" class="admin-mail-refresh" type="button"></button></div><div id="adminMailContent"></div></section>`;adminPanel.appendChild(wrap);positionUi();document.getElementById("adminMailTile").addEventListener("click",()=>{const p=document.getElementById("adminMailPanel"),btn=document.getElementById("adminMailTile");p.hidden=!p.hidden;btn.setAttribute("aria-expanded",p.hidden?"false":"true");if(!p.hidden)void loadMail(true);});document.getElementById("adminMailRefresh").addEventListener("click",()=>void loadMail(true));applyText();}

  function applyText(){const x=t(),wrap=document.getElementById("adminMailWrap");if(!wrap)return;wrap.querySelector(".admin-mail-tile-title").textContent=x.title;wrap.querySelector(".admin-mail-tile-sub").textContent=x.sub;document.getElementById("adminMailPanelTitle").textContent=x.panel;document.getElementById("adminMailRefresh").textContent=x.refresh;renderBadge();if(!document.getElementById("adminMailPanel").hidden)renderList();}
  function renderBadge(){const b=document.getElementById("adminMailBadge"),tile=document.getElementById("adminMailTile");if(!b||!tile)return;const hasUnread=state.unread>0;b.textContent=String(state.unread||0);b.classList.toggle("zero",!hasUnread);b.title=hasUnread?`${state.unread} ${t().new}`:"0";tile.classList.toggle("has-unread",hasUnread);}
  function formatDate(value){const d=new Date(value);if(Number.isNaN(d.getTime()))return"";return d.toLocaleString(lang()==="no"?"nb-NO":lang()==="en"?"en-GB":lang()==="de"?"de-DE":"pl-PL",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"});}
  function renderList(){const box=document.getElementById("adminMailContent");if(!box)return;const x=t();box.replaceChildren();if(state.loading){box.innerHTML=`<div class="admin-mail-status">${x.loading}</div>`;return;}if(!state.loaded){box.innerHTML=`<div class="admin-mail-status">${x.loading}</div>`;return;}if(!state.messages.length){box.innerHTML=`<div class="admin-mail-status">${x.empty}</div>`;return;}const list=document.createElement("div");list.className="admin-mail-list";state.messages.forEach(m=>{const item=document.createElement("article");item.className=`admin-mail-item${m.unread?" unread":""}`;const top=document.createElement("div");top.className="admin-mail-item-top";const sub=document.createElement("div");sub.className="admin-mail-subject";sub.textContent=m.subject||"[EUROPRIS]";const date=document.createElement("div");date.className="admin-mail-date";date.textContent=formatDate(m.date||m.createdAt);top.append(sub,date);const meta=document.createElement("div");meta.className="admin-mail-meta";meta.textContent=[m.type?`${x.type}: ${m.type}`:"",m.contact&&m.contact!=="nie podano"?`${x.contact}: ${m.contact}`:"",m.appVersion?`${x.version}: ${m.appVersion}`:""].filter(Boolean).join(" • ");const msg=document.createElement("div");msg.className="admin-mail-message";msg.textContent=m.message||"";const actions=document.createElement("div");actions.className="admin-mail-actions";const read=document.createElement("button");read.type="button";read.textContent=m.unread?x.read:x.readDone;read.disabled=!m.unread;read.addEventListener("click",async()=>{read.disabled=true;try{const r=await jsonp("feedback_mark_read",{messageId:m.id});if(r?.ok){m.unread=false;state.unread=Math.max(0,state.unread-1);renderBadge();renderList();}else read.disabled=false;}catch{read.disabled=false;}});actions.append(read);item.append(top,meta,msg,actions);list.append(item);});box.append(list);}

  async function loadMail(force=false){if(!isAndrzejAdmin())return;if(state.loading)return;if(state.loaded&&!force){renderList();return;}state.loading=true;renderList();try{const data=await jsonp("feedback_inbox");if(!data?.ok)throw new Error("api");state.unread=Number(data.unread)||0;state.messages=Array.isArray(data.messages)?data.messages:[];state.loaded=true;}catch{state.loaded=true;state.messages=[];const box=document.getElementById("adminMailContent");if(box)box.innerHTML=`<div class="admin-mail-status">${t().error}</div>`;}finally{state.loading=false;renderBadge();renderList();}}
  function syncVisibility(){ensureUi();positionUi();const wrap=document.getElementById("adminMailWrap");if(!wrap)return;const allowed=isAndrzejAdmin();wrap.hidden=!allowed;if(!allowed){const p=document.getElementById("adminMailPanel"),btn=document.getElementById("adminMailTile");if(p)p.hidden=true;if(btn)btn.setAttribute("aria-expanded","false");return;}applyText();if(!state.loaded)void loadMail(false);}
  function start(){ensureUi();syncVisibility();const observer=new MutationObserver(()=>setTimeout(syncVisibility,20));const admin=document.getElementById("adminPanel"),profile=document.getElementById("adminProfileSection"),title=document.getElementById("adminTitle"),body=document.body;if(admin)observer.observe(admin,{attributes:true,attributeFilter:["hidden","style"]});if(profile)observer.observe(profile,{attributes:true,attributeFilter:["hidden","style"]});if(title)observer.observe(title,{childList:true,subtree:true,characterData:true});if(body)observer.observe(body,{childList:true,subtree:true});document.addEventListener("click",e=>{if(e.target.closest(".language")||e.target.closest("[data-lang]"))setTimeout(()=>{applyText();syncVisibility();},80);},true);setInterval(syncVisibility,500);setInterval(()=>{if(isAndrzejAdmin())void loadMail(true);},120000);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
})();